### ISSUE TITLE
Service 'web' failed to build : Build failed

### ISSUE THREAD

**Issue by verynicocool** [mikeizbicki/cmc-csci143#280]
Whenever I run the command `docker-compose -f docker-compose.prod.yml up -d --build` I get the following error:

```
Step 9/28 : RUN flake8 --ignore=E501,F401 .
 ---> Running in e56ab5ec17f9
./project/__init__.py:8:1: E303 too many blank lines (3)
./project/__init__.py:23:1: E302 expected 2 blank lines, found 1
./project/__init__.py:27:1: E302 expected 2 blank lines, found 1
The command '/bin/sh -c flake8 --ignore=E501,F401 .' returned a non-zero code: 1
ERROR: Service 'web' failed to build : Build failed
```

My `docker-compose.prod.yml` file is here: 

```
version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 2123:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
```
And my docker-compose logs output:

```
db_1     | The files belonging to this database system will be owned by user "postgres".
db_1     | This user must also own the server process.
db_1     |
db_1     | The database cluster will be initialized with locale "en_US.utf8".
db_1     | The default database encoding has accordingly been set to "UTF8".
db_1     | The default text search configuration will be set to "english".
db_1     |
db_1     | Data page checksums are disabled.
db_1     |
db_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1     | creating subdirectories ... ok
db_1     | selecting dynamic shared memory implementation ... posix
db_1     | selecting default max_connections ... 100
db_1     | selecting default shared_buffers ... 128MB
db_1     | selecting default time zone ... UTC
db_1     | creating configuration files ... ok
db_1     | running bootstrap script ... ok
db_1     | sh: locale: not found
db_1     | 2023-02-19 00:27:10.580 UTC [30] WARNING:  no usable system locales were found
db_1     | performing post-bootstrap initialization ... ok
db_1     | syncing data to disk ... ok
db_1     |
db_1     |
db_1     | Success. You can now start the database server using:
db_1     |
db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1     |
db_1     | initdb: warning: enabling "trust" authentication for local connections
db_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_1     | --auth-local and --auth-host, the next time you run initdb.
db_1     | waiting for server to start....2023-02-19 00:27:11.427 UTC [36] LOG:  starting PostgreSQL 13.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
db_1     | 2023-02-19 00:27:11.427 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2023-02-19 00:27:11.430 UTC [37] LOG:  database system was shut down at 2023-02-19 00:27:11 UTC
db_1     | 2023-02-19 00:27:11.433 UTC [36] LOG:  database system is ready to accept connections
db_1     |  done
db_1     | server started
db_1     | CREATE DATABASE
db_1     |
db_1     |
db_1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1     |
db_1     | waiting for server to shut down....2023-02-19 00:27:11.571 UTC [36] LOG:  received fast shutdown request
db_1     | 2023-02-19 00:27:11.571 UTC [36] LOG:  aborting any active transactions
db_1     | 2023-02-19 00:27:11.574 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
db_1     | 2023-02-19 00:27:11.574 UTC [38] LOG:  shutting down
db_1     | 2023-02-19 00:27:11.580 UTC [36] LOG:  database system is shut down
db_1     |  done
db_1     | server stopped
db_1     |
db_1     | PostgreSQL init process complete; ready for start up.
db_1     |
db_1     | 2023-02-19 00:27:11.702 UTC [1] LOG:  starting PostgreSQL 13.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
db_1     | 2023-02-19 00:27:11.702 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2023-02-19 00:27:11.702 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2023-02-19 00:27:11.703 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2023-02-19 00:27:11.705 UTC [51] LOG:  database system was shut down at 2023-02-19 00:27:11 UTC
db_1     | 2023-02-19 00:27:11.709 UTC [1] LOG:  database system is ready to accept connections
web_1    | Waiting for postgres...
web_1    | PostgreSQL started
web_1    |  * Serving Flask app 'project/__init__.py'
web_1    |  * Debug mode: on
web_1    | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
web_1    |  * Running on all addresses (0.0.0.0)
web_1    |  * Running on http://127.0.0.1:5000
web_1    |  * Running on http://172.27.0.3:5000
web_1    | Press CTRL+C to quit
web_1    |  * Restarting with stat
web_1    |  * Debugger is active!
web_1    |  * Debugger PIN: 777-918-166
```

I can't seem to find and error listed within the logs but I cant seem to get this web built. Any ideas?
