### ISSUE TITLE
run_test error for twitter postgres hw 

### ISSUE THREAD

**Issue by giffiecode** [mikeizbicki/cmc-csci143#479]
I've updated my port in the `docker-compose.yml` file. However, when I try running the test, I got this error 

```
Yuechen.Pei.23@lambda-server:~/twitter_postgres$ docker-compose exec pg ./run_tests.sh
/home/Yuechen.Pei.23/.local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
```

how to resolve this?

**Comment by mikeizbicki** [comment]
This is a warning (not an error).  It's being generated by the `docker-compose` command on the lambda server (and not by the `run_tests.sh` script inside the container) because the version of python used on the lambda server is deprecated (and `docker-compose` is written in python).

Probably you've been getting this same warning every time you've been running `docker-compose` commands in class so far.  Everything should still work fine.

**Comment by giffiecode** [comment]
Thanks for the clarification. However the problem is I'm not seeing the test results. The above warning is all I'm seeing after running `docker-compose exec pg ./run_tests.sh`. How to view the test results?

**Comment by abizermamnoon** [comment]
Hi Mike, I am having a similar issue:

```
ssh Abizer.Mamnoon.25@lambda.compute.cmc.edu -p 5055 -L localhost:34325:localhost:5432
```

Here is my docker-compose.yml file:
```
version: '3.3'

services:
  pg_denormalized:
    build: services/pg_denormalized
    volumes:
      - ./:/tmp/db
      - pg_denormalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
        - 15432:5432

  pg_normalized:
    build: services/pg_normalized
    volumes:
      - ./:/tmp/db
      - pg_normalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 34325:5432

volumes:
    pg_normalized:
    pg_denormalized:
```

I get this error:
```
lambda-server:~/bigdata/twitter_postgres (master *=) $ sh run_tests.sh postgresql://postgres:34325
sql/complex_01.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
sql/complex_02.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
sql/complex_03.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
sql/complex_04.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
sql/complex_05.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
sql/simple_01.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
sql/simple_02.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
sql/simple_03.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
sql/simple_04.sql psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
fail
```
I also checked to make sure that psql was running:
```
lambda-server:~/bigdata/twitter_postgres (master *=) $ psql postgresql://postgres:
pass@localhost:34325
psql (10.23 (Ubuntu 10.23-0ubuntu0.18.04.1), server 16.2 (Debian 16.2-1.pgdg110+2))
WARNING: psql major version 10, server major version 16.
         Some psql features might not work.
Type "help" for help.

postgres=#
```
