### ISSUE TITLE
Unable to locate manage.py create_db

### ISSUE THREAD

**Issue by ezlee0101** [mikeizbicki/cmc-csci143#642]
I am stuck on the Production Docker part of the homework. I have been able to run create_db up until now so I'm confused to why it's not working now when i try to use the non-root user. 

After updating the ``web`` service in docker,
```
web:
  build:
    context: ./services/web
    dockerfile: Dockerfile.prod
  command: gunicorn --bind 0.0.0.0:5000 manage:app
  ports:
    - 5001:5000
  env_file:
    - ./.env.prod
  depends_on:
    - db
```

and trying out

```
$ docker-compose -f docker-compose.prod.yml down -v
$ docker-compose -f docker-compose.prod.yml up -d --build
```

when I run this command
```
$ docker-compose -f docker-compose.prod.yml exec web python manage.py create_db
```

I am getting this error and can't figure out the problem.
```
Usage: manage.py create_db [OPTIONS]
Try 'manage.py create_db --help' for help.

Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.
```

Is there a way to fix this? Thank you.
